version: "3"

services:
  pilot-discovery:
    image: docker.io/istio/pilot:1.11.3
    command:
      - discovery
      - --meshConfig
      - /etc/istio/config/mesh
      - --registries=
      - --log_output_level=debug
    environment:
      - ENABLE_CA_SERVER=false
      - FILE_MOUNTED_CERTS=false
      - ISTIO_META_NAMESPACE=default
      - PILOT_CERT_PROVIDER=custom
    volumes:
      - ./config/mesh-config.yaml:/etc/istio/config/mesh
      - ./config-sources:/etc/istio/config-sources

  istio-ingressgateway:
    image: docker.io/istio/proxyv2:1.11.3
    command:
      - proxy
      - router
      - --proxyLogLevel=debug
    environment:
      - XDS_ROOT_CA=SYSTEM
      - ENABLE_CA_SERVER=false
      - FILE_MOUNTED_CERTS=true
      - POD_NAME=router
      - POD_NAMESPACE=default
      - ISTIO_META_CONFIG_NAMESPACE=default
      - |
        ISTIO_METAJSON_LABELS={"istio": "ingressgateway", "app": "istio-ingressgateway", "api": "default"}
    volumes:
      - ./config/mesh-config.yaml:/etc/istio/config/mesh
    ports:
      - "8080:80"
      - "15000:15000"
