# Global mesh config.

enableAutoMtls: false
accessLogFile: /dev/stdout
defaultConfig:
  discoveryAddress: pilot-discovery:15010
  controlPlaneAuthPolicy: NONE
  terminationDrainDuration: 5s
  sds:
    enabled: false
configSources:
  - address: fs:///etc/istio/config-sources
